name: Deploy to Pages

on:
  push:
    branches:
      - main
      
jobs:
  build: 
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Setup config
        run: ./scripts/gen_config_pages.sh
      - name: Set up Gleam
        uses: erlef/setup-beam@v1
        with:
          otp-version: "29.0"
          gleam-version: "1.17.0"
          rebar3-version: "3"
          
      - name: Setup Node
        uses: actions/setup-node@v7
        with: 
          node-version: "26.x"
        
      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npx vite build
        
      # - name: Install dependencies
      #   run: gleam deps download
      # - name: Build app
      #   run: gleam run -m lustre/dev build --minify --outdir=dist
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - name: Deploy to pages
        uses: actions/deploy-pages@v4