name: Deploy to Pages

on:
  push:
    branches:
      - main
      
jobs:
  build: 
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: erlef/setup-beam@v1
        with:
          gleam-version: "1.17.0"
      - run: gleam run -m lustre/dev build
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with: 
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4